[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
graphics = { path = "../graphics" }
ecs = { path = "../ecs" }
cgmath = { version = "0.18.0", features = ["serde"]}

winit = "0.30.3"