[package]
name = "server"
version = "0.1.0"
authors = ["Swiiz"]
edition = "2021"

[dependencies]
common = { path = "../common"}
ecs = { path = "../ecs"}
cgmath = { version = "0.18.0", features = ["serde"]}
serde = { version = "1.0", features = ["derive"] }