[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
ecs = { path = "../ecs" }
cgmath = { version = "0.18.0", features = ["serde"]}
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
bimap = "0.6.3"
indexmap = "2.4.0"
serde_json = "1.0.127"
